#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : seaborn
Version  : 0.10.0
Release  : 22
URL      : https://files.pythonhosted.org/packages/af/b8/0c299903a2f6b8170eccf522ec44c3d7bbe4f10427cd90cf9bebf52c9919/seaborn-0.10.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/af/b8/0c299903a2f6b8170eccf522ec44c3d7bbe4f10427cd90cf9bebf52c9919/seaborn-0.10.0.tar.gz
Summary  : seaborn: statistical data visualization
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: seaborn-license = %{version}-%{release}
Requires: seaborn-python = %{version}-%{release}
Requires: seaborn-python3 = %{version}-%{release}
Requires: matplotlib
Requires: numpy
Requires: pandas
Requires: scipy
BuildRequires : buildreq-distutils3
BuildRequires : matplotlib
BuildRequires : numpy
BuildRequires : pandas
BuildRequires : scipy

%description
Seaborn is a library for making statistical graphics in Python. It is built on top of `matplotlib <https://matplotlib.org/>`_ and closely integrated with `pandas <https://pandas.pydata.org/>`_ data structures.

Here is some of the functionality that seaborn offers:

- A dataset-oriented API for examining relationships between multiple variables
- Specialized support for using categorical variables to show observations or aggregate statistics
- Options for visualizing univariate or bivariate distributions and for comparing them between subsets of data
- Automatic estimation and plotting of linear regression models for different kinds dependent variables
- Convenient views onto the overall structure of complex datasets
- High-level abstractions for structuring multi-plot grids that let you easily build complex visualizations
- Concise control over matplotlib figure styling with several built-in themes
- Tools for choosing color palettes that faithfully reveal patterns in your data

Seaborn aims to make visualization a central part of exploring and understanding data. Its dataset-oriented plotting functions operate on dataframes and arrays containing whole datasets and internally perform the necessary semantic mapping and statistical aggregation to produce informative plots.

%package license
Summary: license components for the seaborn package.
Group: Default

%description license
license components for the seaborn package.


%package python
Summary: python components for the seaborn package.
Group: Default
Requires: seaborn-python3 = %{version}-%{release}

%description python
python components for the seaborn package.


%package python3
Summary: python3 components for the seaborn package.
Group: Default
Requires: python3-core
Provides: pypi(seaborn)

%description python3
python3 components for the seaborn package.


%prep
%setup -q -n seaborn-0.10.0
cd %{_builddir}/seaborn-0.10.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582924088
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/seaborn
cp %{_builddir}/seaborn-0.10.0/licences/HUSL_LICENSE %{buildroot}/usr/share/package-licenses/seaborn/3284262e860227419fea272a5ab2a954dae740c0
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/seaborn/3284262e860227419fea272a5ab2a954dae740c0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
